### ISSUE TITLE
Upload app in android Play Store

### ISSUE THREAD

**Issue by maxdobler** [synyx/MeeRoo#7]
App should be available in Play Store.

**Comment by heetel** [comment]
added entry in PlayStore containing:
* icon, banner
* initial screenshot
* short description
* contact data, privacy policy

ToDo:
* upload apk
* age classification

**Comment by maxdobler** [comment]
App is uploaded into store and is waiting for authorization.

**Comment by IzzySoft** [comment]
Would you also consider an alternative download source (for those without Play Store) – e.g. attaching the APK to `releases/` or have it listed with F-Droid?

**Comment by maxdobler** [comment]
Hi @IzzySoft ,
we release .aab files. Is there support in F-Droid? Alternatively I could generate an APK for F-Droid, but I have to read through the docs, because it is the first time we release on F-Droid. So it can take some time, but we will get there. :-)

**Comment by IzzySoft** [comment]
> we release .aab files. Is there support in F-Droid?

No. F-Droid always builds entirely from source – no blobs or proprietary components allowed. From a quick glance, your app seems to qualify: I can see no "untrusted Maven repo" or blobs or other show stoppers (but then, I'm not a dev). So if you want to go for the [official repo](https://f-droid.org/) and need help with that, I could assist you. First step would be opening an [RFP](https://gitlab.com/fdroid/rfp/issues) (request for packaging), which would trigger the F-Droid issue-bot scanning your repo and (hopefully) confirm. If the bot gives its OK, I'd set up a metadata template and one of our integrators would take over, testing the build and finally adding the app (yeah, disclosure: I'm one of the F-Droid maintainers).

> Alternatively I could generate an APK for F-Droid

That would work fine for [my repo](https://apt.izzysoft.de/fdroid), where inclusion criteria are a bit more relaxed. This serves mostly for apps which cannot (yet) reach compliance; hundreds already "went through" and finally "moved over" to the official repo when they got rid of the last show-stopper, and about 400 are more-or-less "permanent residents" at the moment.

> So it can take some time, but we will get there.

Glad to read! That would already cound as your "not being opposed". So shall we give the first-mentioned process a go?
